/* HAKIM Ω Professional Artifact Engine v2 */
(function(){'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=s=>String(s||'hakim-resource').replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,'').slice(0,80)||'hakim-resource';
function normalize(t){return String(t||'').replace(/\r/g,'').replace(/\u00a0/g,' ').trim()}
function inline(s){return esc(s).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`(.+?)`/g,'<code>$1</code>')}
function markdown(t){const lines=normalize(t).split('\n'),out=[];let ul=false,ol=false,table=false;const close=()=>{if(ul){out.push('</ul>');ul=false}if(ol){out.push('</ol>');ol=false}if(table){out.push('</tbody></table>');table=false}};for(let raw of lines){const l=raw.trim();if(!l){close();continue}if(/^\|.*\|$/.test(l)){const cells=l.slice(1,-1).split('|').map(x=>x.trim());if(/^[-: ]+$/.test(cells.join('').replace(/\|/g,'')))continue;if(!table){close();out.push('<table><thead><tr>'+cells.map(c=>'<th>'+inline(c)+'</th>').join('')+'</tr></thead><tbody>');table=true}else out.push('<tr>'+cells.map(c=>'<td>'+inline(c)+'</td>').join('')+'</tr>');continue}close();if(/^###\s+/.test(l)){out.push('<h3>'+inline(l.replace(/^###\s+/,''))+'</h3>');continue}if(/^##\s+/.test(l)){out.push('<h2>'+inline(l.replace(/^##\s+/,''))+'</h2>');continue}if(/^#\s+/.test(l)){out.push('<h2>'+inline(l.replace(/^#\s+/,''))+'</h2>');continue}if(/^[-*]\s+/.test(l)){if(!ul){out.push('<ul>');ul=true}out.push('<li>'+inline(l.replace(/^[-*]\s+/,''))+'</li>');continue}const om=l.match(/^\d+[.)]\s+(.+)/);if(om){if(!ol){out.push('<ol>');ol=true}out.push('<li>'+inline(om[1])+'</li>');continue}out.push('<p>'+inline(l)+'</p>')}close();return out.join('')}
function professionalHtml(title,text,mode='lesson'){return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>@page{size:A4;margin:15mm 15mm 17mm}*{box-sizing:border-box}html,body{margin:0;padding:0}body{font-family:"Noto Naskh Arabic","Amiri","Tahoma",Arial,sans-serif;color:#17202a;background:#edf1f5;font-size:14pt;line-height:1.8}.sheet{max-width:210mm;margin:16px auto;background:#fff;padding:15mm 16mm;min-height:267mm;box-shadow:0 2px 16px #0001}.brand{border-bottom:2px solid #17202a;padding-bottom:9px;margin-bottom:18px}.brand small{font-size:9.5pt}.brand h1{font-size:24pt;margin:3px 0}.meta{font-size:10pt;color:#56606b}.content p{margin:7px 0}.content h2{font-size:18pt;margin:20px 0 8px;border-bottom:1px solid #d8dde2;padding-bottom:4px}.content h3{font-size:15.5pt;margin:15px 0 5px}.content ul,.content ol{margin:7px 0 12px;padding-right:28px}.content li{margin:3px 0}.content table{width:100%;border-collapse:collapse;margin:12px 0;font-size:12.5pt}.content th,.content td{border:1px solid #bfc6ce;padding:7px 8px;vertical-align:top}.content th{font-weight:800}.content code{font-family:monospace}.footer{margin-top:25px;padding-top:8px;border-top:1px solid #d8dde2;font-size:8.5pt;text-align:center}.actions{position:fixed;top:12px;left:12px}.actions button{border:0;border-radius:8px;padding:9px 13px;font:inherit;background:#17202a;color:white}@media print{body{background:#fff;font-size:13.2pt}.sheet{margin:0;max-width:none;box-shadow:none;padding:0;min-height:auto}.actions{display:none}.brand,h2,h3{break-after:avoid}.content table{break-inside:auto}.content tr{break-inside:avoid}.footer{break-inside:avoid}} </style></head><body><div class="actions"><button onclick="window.print()">طباعة / PDF</button></div><main class="sheet"><header class="brand"><small>HAKIM Ω — الاستوديو التعليمي</small><h1>${esc(title)}</h1><div class="meta">${mode==='worksheet'?'ورقة عمل تعليمية':'مورد تعليمي'} • A4 • RTL</div></header><article class="content">${markdown(text)}</article><footer class="footer">بناء جيل المبدعين - مشروع زيتونة التعليمي</footer></main></body></html>`}
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)}
function build(text){const content=normalize(text);if(content.length<40)throw Error('OUTPUT_TOO_SHORT');const first=content.split('\n').find(x=>x.trim())||'مورد تعليمي';return{schema:'HAKIM-RESOURCE/2.0',type:'educational_resource',title:first.replace(/^#+\s*/,''),language:'ar',direction:'rtl',numerals:'eastern-arabic',content,createdAt:new Date().toISOString()}}
window.HAKIM_ENGINE={build,markdown,professionalHtml,exportHtml:r=>download(slug(r.title)+'.html',professionalHtml(r.title,r.content),'text/html;charset=utf-8'),exportJson:r=>download(slug(r.title)+'.json',JSON.stringify(r,null,2),'application/json;charset=utf-8'),exportText:r=>download(slug(r.title)+'.txt',r.content,'text/plain;charset=utf-8'),printPdf:r=>{const w=window.open('','_blank');if(!w)throw Error('POPUP_BLOCKED');w.document.write(professionalHtml(r.title,r.content));w.document.close();setTimeout(()=>w.print(),700)}};
})();
