/* HAKIM Ω Game Engine v2 — deterministic, lightweight, downloadable */
(function(){'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const download=(name,text,type='text/html')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
 function shell(title,body,script){return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><style>@page{size:A4;margin:1.5cm}body{font-family:system-ui,sans-serif;margin:0;background:#f5f7fa;color:#17202a}main{max-width:760px;margin:auto;padding:20px}.card{background:#fff;border:1px solid #ddd;border-radius:20px;padding:24px}.choices{display:flex;flex-wrap:wrap;gap:8px;margin:18px 0}button{padding:13px 18px;border:0;border-radius:12px;background:#111827;color:#fff;font:inherit;cursor:pointer}.feedback{min-height:34px;margin-top:14px;font-weight:700}.score{margin-top:14px;font-weight:700}@media print{button{display:none}body{background:white}main{max-width:none;padding:0}.card{border:0}}</style></head><body><main><div class="card">${body}</div></main><script>${script}</script></body></html>`}
 function countGame(r){const title=r.title||'لعبة العدد ٢';const html=shell(title,`<h1>${esc(title)}</h1><p>انظر إلى المجموعة ثم اختر العدد الذي يمثلها.</p><div id="items" style="font-size:44px;letter-spacing:10px">● ●</div><div class="choices"><button data-v="١">١</button><button data-v="٢">٢</button><button data-v="٣">٣</button></div><div class="feedback" id="f"></div><div class="score" id="s">النقاط: ٠</div>`,`let score=0;document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const ok=b.dataset.v==='٢';document.getElementById('f').textContent=ok?'أحسنت! إجابة صحيحة 🌟':'حاول مرة أخرى.';if(ok)score++;document.getElementById('s').textContent='النقاط: '+score});`);download('لعبة-تعليمية.html',html);return html}
 function choiceGame(title='لعبة الاختيار',question='اختر الإجابة الصحيحة',answer='٢',choices=['١','٢','٣']){const buttons=choices.map(x=>`<button data-v="${esc(x)}">${esc(x)}</button>`).join('');return shell(title,`<h1>${esc(title)}</h1><p>${esc(question)}</p><div class="choices">${buttons}</div><div class="feedback" id="f"></div><div class="score" id="s">النقاط: ٠</div>`,`let score=0;document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const ok=b.dataset.v===${JSON.stringify(answer)};document.getElementById('f').textContent=ok?'أحسنت! إجابة صحيحة 🌟':'حاول مرة أخرى.';if(ok)score++;document.getElementById('s').textContent='النقاط: '+score});`)}
 window.HAKIM_GAME={countGame,choiceGame,download};
})();
